spring.application.name=user-profile-service
spring.config.import=vault://
spring.cloud.vault.enabled=true

spring.datasource.url=jdbc:h2:mem:userprofiledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update