server.port=${PORT:8080}
spring.application.name=user-profile-service
spring.config.import=optional:vault://
spring.cloud.vault.enabled=${SPRING_CLOUD_VAULT_ENABLED:false}

spring.datasource.url=jdbc:h2:mem:userprofiledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${db.username:${DB_USERNAME:sa}}
spring.datasource.password=${db.password:${DB_PASSWORD:password123}}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update